#!/bin/bash

## find the maximum difference between columns of two files and the maximum
## absolute value of each column of the first one

## pipe through awk '{ r=$1/$2 ; print r; }' to get the relative errors

file1=$1
file2=$2

paste ${file1} ${file2} | \
    awk 'function abs(x){return ((x < 0.0) ? -x : x)}
    BEGIN { ncol=NF/2 ; {max[ncol] = -inf; fmax[ncol] = -inf } } {
      ncol=NF/2 ;
      for (i = 1 ; i <= ncol ; i++ ) {
        j = i+ncol ; m = abs($i-$j) ;
        if ( m > max[i] ) { max[i] = m ; }
	m = abs($i)
        if ( m > fmax[i] ) { fmax[i] = m ; }
      }
     }
    END { 
   for (i = 1 ; i <= ncol ; i++ ) { 
   printf "%1.16e %1.16e\n", max[i], fmax[i]}
  }'
