Indexing and lookup operations
Indexing functions for accessing tree data structures.
Functions
guint64 wbfmm_box_index (guint32 i, guint32 j, guint32 k)
gint wbfmm_box_location (guint64 idx, guint32 *i, guint32 *j, guint32 *k)
gint wbfmm_box_interaction_list_4 (guint level, guint64 idx, guint64 *list, gboolean sort)
Find the local interaction list for a specified box.
Detailed Description
Indexing functions for accessing tree data structures.
Functions for indexing and lookup in tree data structures, including finding neighbours and interaction lists, based on the methods of Gumerov, Duraiswami, and Borovikov, Data Structures, Optimal Choice of Parameters, and Complexity Results for Generalized Multilevel Fast Multipole Methods in d Dimensions, 2003
http://users.umiacs.umd.edu/~gumerov/PDFs/cs-tr-4458.pdf
Code for Morton indexing operations is taken from: https://www.forceflow.be/2013/10/07/morton-encodingdecoding-through-bit-interleaving-implementations/
Function Documentation
guint64 wbfmm_box_index (guint32 i, guint32 j, guint32 k)
Generate a Morton index for a box with corner at integer coordinates (i,j,k).
Parameters
i x index of bottom left hand corner;
j y index of bottom left hand corner;
k z index of bottom left hand corner.
Returns
Morton index for (i, j, k).
Referenced by wbfmm_box_interaction_list_4().
gint wbfmm_box_interaction_list_4 (guint level, guint64 idx, guint64 * list, gboolean sort)
Find the local interaction list for a specified box.
Find the indices of boxes on a given level of a tree which interact directly with a specified box (list 4 in Gumerov and Duraiswami's notation). These are boxes which are children of neighbours of the parent of the specified box, and separated from it by at least one box. On exit list contains entries made up of two integers, a box index and the index for looking up rotation and translation operations.
Parameters
level tree level for list;
idx index of box whose interaction list is to be found;
list on exit contains list of interacting boxes and specification of rotation required;
sort if TRUE, sort list so that boxes with the same rotation angles are grouped together
Returns
number of entries in list
References wbfmm_box_index(), and wbfmm_box_location().
gint wbfmm_box_location (guint64 idx, guint32 * i, guint32 * j, guint32 * k)
Compute indices for bottom left hand corner of box defined by its Morton index, as generated by wbfmm_box_index
Parameters
idx index of box corner;
i on output, x index of bottom left hand corner of box;
j on output, y index of bottom left hand corner of box;
k on output, z index of bottom left hand corner of box.
Returns
0 on success.
Referenced by wbfmm_box_interaction_list_4().