#!/bin/bash

BIN=../../tools

sfile=monopoles-hh.dat
##sfile=curl.dat
##sfile=dipoles-hh.dat
ffile=field.dat
dfile=direct.dat
fmmfile=fmm.dat
avxfile=avx.dat
##swfile=swfmm.dat
bw=-B
depth=4
nthread=1
order_r=16
order_s=16
targets=
curl=
k=1.3

##${BIN}/wbfmm-direct-calc ${curl} -k ${k} -f ${ffile} -s ${sfile} > ${dfile}

${BIN}/wbfmm-tree-calc-avx ${curl}  -k ${k} -b -B -d ${depth} \
      -R ${order_r} -S ${order_s} -T ${nthread} \
      -f ${ffile} -s ${sfile} ${targets} > ${avxfile}

${BIN}/wbfmm-tree-calc-avx ${curl}  -k ${k} -b -d ${depth} \
      -R ${order_r} -S ${order_s} -T ${nthread} \
      -f ${ffile} -s ${sfile} ${targets} > ${avxfile}
