#!/bin/bash

FMM=../tests/wbfmm-tree-calc
DIRECT=../tests/wbfmm-direct-calc

depth=4
k=1.5
sources=sources.dat
field=fpoints.dat

#${FMM} -d ${depth} -s ${sources} -k ${k} -f ${field} > field-fmm.dat
#${DIRECT} -s ${sources} -k ${k} -f ${field} > field-direct.dat

fmmr=(`cut -d " " -f 4 field-fmm.dat`)
fmmi=(`cut -d " " -f 5 field-fmm.dat`)
dctr=(`cut -d " " -f 4 field-direct.dat`)
dcti=(`cut -d " " -f 5 field-direct.dat`)

np=${#fmmr[@]}

emax=-1
fmax=-1

for ((i=0; i<${np}; i++ ))
##for ((i=0; i<1; i++ ))
do
    ##echo ${i}
    fmmri=`echo ${fmmr[${i}]} | sed -e s/e+/*10^/ -e s/e-/*10^-/`
    fmmii=`echo ${fmmi[${i}]} | sed -e s/e+/*10^/ -e s/e-/*10^-/`
    ##echo ${fr}
    dctri=`echo ${dctr[${i}]} | sed -e s/e+/*10^/ -e s/e-/*10^-/`
    dctii=`echo ${dcti[${i}]} | sed -e s/e+/*10^/ -e s/e-/*10^-/`
    eqn=sqrt\(\(\(${fmmri}\)-\(${dctri}\)\)^2+\(\(${fmmii}\)-\(${dctii}\)\)^2\)

    ##echo ${eqn}
    ee=`echo ${eqn} | bc -l`
    mag=`echo sqrt\(\(${dctri}\)^2+\(${dctii}\)^2\) | bc -l`
    emax=`echo max\(${emax},${ee}\) | bc -l max.bc`
    fmax=`echo max\(${fmax},${mag}\) | bc -l max.bc`
done

Linf=`echo ${emax}/${fmax} | bc -l`

echo ${emax} ${fmax} ${Linf}
