#!/bin/bash

depth=4
#bw=-B
bw=
gradient=-g

../tests/wbfmm-laplace-tree-calc -b -d ${depth} -f field.dat \
				 -R 16 -S 16 ${bw} ${gradient} \
				 -s monopoles.dat \
				 -t 1e-9 > monopole-laplace-fmm.dat

../tests/wbfmm-laplace-direct-calc -f field.dat ${gradient} \
				   -s monopoles.dat > \
				   monopole-laplace-direct.dat
